### ISSUE TITLE
Assert statement required for Week 10

### ISSUE THREAD

**Issue by yaowei-soc** [AY2021S2-CS2103T-T12-3/tp#110]
- [x] Justin
- [x] Yao Wei
- [x] Boon Ji
- [x] KI
- [x] Yi Ping

![image](https://user-images.githubusercontent.com/77482180/112334978-cf23b780-8cf6-11eb-98d9-4f902e2a0d6d.png)

**Comment by yaowei-soc** [comment]
@darkdestry-t have you completed the assertions? https://nus-cs2103-ay2021s2.github.io/dashboards/contents/tp-progress.html

**Comment by tanboonji** [comment]
Everyone has completed this requirement. Closing issue.
