### ISSUE TITLE
Why the JAR file is large?

### ISSUE THREAD

**Issue by damithc** [AY2021S2-CS2103T-T12-3/tp#142]
Guys, why is your JAR file large (85Mb)? Usually, tP JAR files are about 10-20Mb.

@yaowei-soc 
@tanboonji
@DarkDestry-t
@justgnohUG
@oeiyiping

**Comment by darkdestry-t** [comment]
Investigating right now.

**Comment by damithc** [comment]
Possibly caused by these libraries in your build.gradle,
```
    implementation group: 'org.openjfx', name: 'javafx-web', version: javaFxVersion, classifier: 'win'
    implementation group: 'org.openjfx', name: 'javafx-web', version: javaFxVersion, classifier: 'mac'
    implementation group: 'org.openjfx', name: 'javafx-web', version: javaFxVersion, classifier: 'linux'
    implementation group: 'org.openjfx', name: 'javafx-media', version: javaFxVersion, classifier: 'win'
    implementation group: 'org.openjfx', name: 'javafx-media', version: javaFxVersion, classifier: 'mac'
    implementation group: 'org.openjfx', name: 'javafx-media', version: javaFxVersion, classifier: 'linux'
```

**Comment by darkdestry-t** [comment]
Issue is due to the webkit package

![image](https://user-images.githubusercontent.com/77267650/113381415-7f598600-93b1-11eb-9b3a-bada478cf3ab.png)

Is the large file an issue?

**Comment by darkdestry-t** [comment]
User story #96 

We implemented a web view using javafx webview

**Comment by oeiyiping** [comment]
Hi Prof Damith, the javafx webkit and media packages are used to open HTML files from within the app. Our intention is to allow users to open the user guide directly within the app itself. May I know if the large file size is an issue (and negatively affect the grading)? If so, we will remove the packages and explore other options.

**Comment by damithc** [comment]
> User story #96
> 
> We implemented a web view using javafx webview

I see. In that case the large JAR size is unavoidable. It's fine to leave it be. Thanks for checking.
