### ISSUE TITLE
Remembering the commands and arguments is hard

### ISSUE THREAD

**Issue by yaowei-soc** [AY2021S2-CS2103T-T12-3/tp#16]
As a user I should be shown a list of commands or arguments that I can use such that I don't have to remember all the possible arguments and commands available.

Update:

- Listing of the commands is already implemented in #80 however, it does not extend in aliases that was implemented in #73
- Do we want to extend the autocomplete into the flags (e.g. -p, -a, -n, etc) and arguments (e.g. phone numbers, email addresses, etc)

**Comment by yaowei-soc** [comment]
@justgnohUG are you taking this issue? Seems like it is related to #124

**Comment by justgnohUG** [comment]
Closed in #124
