### ISSUE TITLE
Personal Portfolio Page

### ISSUE THREAD

**Issue by darkdestry-t** [AY2021S2-CS2103T-T12-3/tp#206]
Draft
- [x] @tanboonji 
- [x] @oeiyiping 
- [x] @darkdestry-t
- [x] @justgnohUG 
- [x] @yaowei-soc 

Finalize
- [x] @tanboonji 
- [x] @oeiyiping 
- [x] @darkdestry-t
- [x] @justgnohUG 
- [x] @yaowei-soc

**Comment by tanboonji** [comment]
Closed as everyone has finalized their PPP.
