### ISSUE TITLE
JavaFX API version 15.0.1 is used instead of version 11

### ISSUE THREAD

**Issue by tanboonji** [AY2021S2-CS2103T-T12-3/tp#216]
Would there be any issues with using JavaFX API version 15.0.1 in our application? Should we change it back to use version 11 (same version with our Java).

![image](https://user-images.githubusercontent.com/12221867/114000906-03b67800-988e-11eb-86ab-4f0e87756bf1.png)

**Comment by oeiyiping** [comment]
I noticed this as well, I found out that this always occurs after using SceneBuilder (probably auto-edited the fxml file to be v15). Did not encounter any issue regarding this matter, but I feel that we should edit the affected fxml files back to v11 before submission.
