### ISSUE TITLE
Update screenshots for UG

### ISSUE THREAD

**Issue by yaowei-soc** [AY2021S2-CS2103T-T12-3/tp#245]
- Quickstart image
- Help window image
- Add person image
- Edit person image
- Find person image
- Delete person image
- Select person image
- Email person image (to add)
- Command auto completion (to add)
- Alias command image (to add)
- Filter command (to add)
- Tag command (to add)

**Comment by oeiyiping** [comment]
Note for all working on UG: when adding UG screenshots: it was recommended that the screenshotted data should match the examples provided in the UG. Currently there are some existing screenshot-example mismatch that was criticised during UG consultation.

eg. Feature Section - Add
![image](https://user-images.githubusercontent.com/70749318/114337298-7cb21a00-9b83-11eb-8aa1-b221bc6cce8b.png)
Screenshot data (Alex Yeo and friends) does not match the provided examples (John Doe and co.).

Current screenshots in the UG are also not updated in that they do not include the newly added fields (job and company).
