### ISSUE TITLE
Add common conventions into Developer Guide

### ISSUE THREAD

**Issue by yaowei-soc** [AY2021S2-CS2103T-T12-3/tp#52]
## Git Commit Naming Convention

For Git commit naming convention, add https://www.conventionalcommits.org/en/v1.0.0/
Example:
`docs: Update AboutUs to include EOL` vs `docs: update AboutUs to include EOL` @ https://github.com/AY2021S2-CS2103T-T12-3/tp/commit/cc991609afe9d58f3709c2e9d5c3b416bae72dfe

- [x] Discuss & standardize Git commit naming convention
- [ ] Document naming convention for easy reference

## Git Branch Naming Convention

For Git branch naming convention, no particular convention. My preference is to follow this convention:
- feature branches `feature/{issue number}-{name}`
- hotfix branches `hotfix/{issue number}-{name}`
- documentation branches `docs/{issue number}-{name}`

Example:
- justgnohUG:docs/add-image
- oeiyiping:docs/update-aboutus
- darkdestry-t:docs/aboutus-image
- yaowei-soc:docs/41-profile-photo
- tanboonji:docs/34-user-guide

- [x] Discuss & standardize Git branch naming convention
- [ ] Document naming convention for easy reference

## Pull Request Naming Convention

We currently do not have a convention for naming PR. An example can be https://namingconvention.org/git/pull-request-naming.html

#[Ticket_ID] PR description

- [x] Discuss & standardize PR naming convention
- [ ] Document naming convention for easy reference

**Comment by yaowei-soc** [comment]
**Git Commit Name Convention**

We will stick to conventional commit style, but we will capitalize the first letter after the colon.

Recommended examples:

- docs: Update [readme.md](http://readme.md)
- docs: Update [README.md](http://readme.md)

The general consensus is that if it conveys what this commit does, it's fine.


**Git Branch Naming**

Naming of the branch doesn't really matter as long as it makes sense.

https://se-education.org/guides/conventions/git.html

If a branch is related to an issue, it is recommended to use the format `{issue number}-some-keywords-from-the-issue`

Recommended examples:

- docs/69-update-readme
- feature/22-add-storage-backup

**Pull Request Naming Convention**

No specific PR naming convention, as long as it conveys information on what that PR does.
Can use conventional commit style or write your own short description.

**Comment by tanboonji** [comment]
Conventions are not compulsory to be added for DG and will be tracked and discussed offline. Closing issue.
