### ISSUE TITLE
Incorrect parsing of field values for command prefixes that share the same front substring

### ISSUE THREAD

**Issue by oeiyiping** [AY2021S2-CS2103T-T12-3/tp#82]
eg. `add ... -p 12345 -pa456 ...`
The prefixes are `-p` and `-pa`, both share the same front substring of `-p`.
As such, the parsed value of  the `-p` field will be a456 (wrong), instead of 12345 (correct).

**Comment by darkdestry-t** [comment]
Resolves #149
