### ISSUE TITLE
DG improvements

### ISSUE THREAD

**Issue by darkdestry-t** [AY2021S2-CS2103T-T12-3/tp#90]
Diagram additions

- [x] Justin
- [x] Yao Wei
- [x] Boon Ji
- [x] KI
- [x] Yi Ping

Last person to close the issue

https://nus-cs2103-ay2021s2.github.io/website/schedule/week10/project.html#4-update-the-dg-with-design-details

Update the Developer Guide as follows:
- Each member should describe the implementation of at least one enhancement she has added (or planning to add).
- Expected length: 1+ page per person
- The description can contain things such as,
  - How the feature is implemented (or is going to be implemented).
  - Why it is implemented that way.
  - Alternatives considered.

**Comment by yaowei-soc** [comment]
Since everyone has already updated their section of the DG for week 10, I'm closing this issue.

You can check your tP progress here: https://nus-cs2103-ay2021s2.github.io/dashboards/contents/tp-progress.html
