### ISSUE TITLE
Command in aliases does not appear in autocomplete panel

### ISSUE THREAD

**Issue by tanboonji** [AY2021S2-CS2103T-T12-3/tp#97]
I want to be able to see my aliases in the autocomplete panel so that I can autocomplete my aliases too.

**Comment by yaowei-soc** [comment]
Closing issue since it is implemented in PR #121

**Comment by tanboonji** [comment]
> Closing issue since it is implemented in PR #121

Not implemented in PR #121 yet.

**Comment by tanboonji** [comment]
Closing issue as it will not be implemented/fixed in Milestone 1.4.
